Tuple fix
pysamp/PySAMP pull request #117
Opened 2023-05-31 19:21 UTC by Ykpauneu

Removed all tuple args from functions and replaced with separate args

2023-05-31 19:24 UTC, Ykpauneu commented
Added import fix from https://github.com/pysamp/PySAMP/pull/116

2023-06-09 15:24 UTC, dennorske commented
Why are two modules (Dialog / Menu) in the root folder?

2023-06-09 15:25 UTC, dennorske commented on dialog.py
Odd placement

2023-06-09 15:25 UTC, dennorske commented on menu.py
Same here, odd placement

2023-06-09 15:26 UTC, dennorske requested changes
Make sure there are no odd file placements and/or justify the changes in your PR

2023-06-13 20:00 UTC, Ykpauneu commented on dialog.py
Fixed

2023-06-13 20:00 UTC, Ykpauneu commented on menu.py
Fixed too

2023-06-22 11:52 UTC, dennorske approved these changes

2023-06-22 11:52 UTC, dennorske commented on pysamp/player.py
>          :param tuple conf: A tuple containing the weapon id and ammo.
We should make sure the docstrings are modified as well. I can do this if you want, but worth keeping in mind for future changes (so we don't get drift ^^)

2023-06-22 11:52 UTC, dennorske commented
Thanks a lot! Merging.

2023-06-22 11:53 UTC, merged