Docs for events
pysamp/PySAMP pull request #140
Opened 2024-12-30 21:08 UTC by gsmj

2024-12-30 22:30 UTC, gsmj commented
![изображение](https://github.com/user-attachments/assets/6df569a9-9581-4046-8672-b4c0e5db12fd)
looks fime

2025-05-14 14:19 UTC, dennorske requested changes

2025-05-14 14:19 UTC, dennorske commented on pysamp/player.py
> +        return (cls(player_id), Vehicle(vehicle_id), is_passenger)
I tried to explain the concept of the events here: https://github.com/pysamp/PySAMP/pull/134#issuecomment-2124386199

Basically, the `Parameters` we need to document here is not the "input" values to the function, but the return values the function gives us.
See at line 2628: 
```py
return (cls(player_id), Vehicle(vehicle_id), is_passenger)
```

This event returns:
1. An instance of a Player
2. An instance of a Vehicle
3. A bool

Therefore, it is wrong to document that the event will give us
1. int
2. int
3. bool.

Do you agree? :)

2025-05-14 14:19 UTC, dennorske commented on pysamp/player.py
> +            Please use the event ``player.on_click_map`` instead.
Nice catch! 🙏

2025-05-14 14:19 UTC, dennorske commented on pysamp/player.py
> +            - Keep in mind this function can be inaccurate in some cases.
Replace function with "event" to keep consistency

2025-05-14 14:22 UTC, dennorske commented
I am also wondering if we should not document the inner callbacks for the events - Ideally we should document these as proper callbacks. Maybe we can somehow tell sphinx that we want them to be annotated as events and not as classmethods? Wondering if you have some experience with this @Cheaterman

2025-05-16 17:55 UTC, gsmj commented on pysamp/player.py
> +        return (cls(player_id), Vehicle(vehicle_id), is_passenger)
100% agree. IIRC I even had a conversation with @Cheaterman about this. I'll fix that soon

2025-05-17 10:13 UTC, Cheaterman commented on pysamp/player.py
> +            - Keep in mind this function can be inaccurate in some cases.
On top of that, if we really wanted to be thorough, we might want to document the behavior of lagcomp setting here - IIRC it affects whether `OnPlayerGiveDamage` or `OnPlayerTakeDamage` should be used?

2025-05-17 10:22 UTC, Cheaterman commented
Great question! I haven't done that in the past, but from a quick glance at Sphinx docs, the way to achieve this might be to develop a [autodoc extension](https://www.sphinx-doc.org/en/master/development/tutorials/autodoc_ext.html) that will apply some special behavior to our `@event` decorator ; I'll ask on IRC and see if it's the right call :-)

2025-05-17 10:36 UTC, Cheaterman commented
Another small detail I mentioned on Discord but will repost here - it's probably a good idea to document which SAMP/open.mp callback is being wrapped by each event, and provide a link to the corresponding open.mp documentation ; the first part so that people coming from Pawn can be 100% sure which event corresponds to the callback they're looking for, and the second part in case eg open.mp adds extra warnings or behavior changes to the official documentation (I don't think we'll be keeping it in sync constantly, probably too much maintenance burden).

2025-05-18 15:40 UTC, dennorske approved these changes
I approve the changes and I think they are valuable to get in to our documentation as a "for now they are good enough" kind of deal.

Thank you very much @gsmj !

I however want us to clarify and label the events properly via sphinx, so we will have to follow up on that later.

2025-08-05 18:23 UTC, merged